mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),
    path('polls/',include('polls.urls')),
    path('simuu/',include('simuu.urls'))
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
	path('', views.index, name='index'),
	path('details/<int:question_id>/',views.details,name='details'),
	path('result/<int:question_id>/',views.result,name='result'),
	path('vote/<int:question_id>/',views.vote,name='vote')
	#path('all/',views.viewQuestions,name='all')
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = 'root'
urlpatterns = [
    path('', views.index, name="index"),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


###     Clase Autor
##########################
class Autor(models.Model):
    nome = models.CharField(max_length=80)

    class Meta:
        ordering = ['nome']
        verbose_name_plural = 'Autores'
    def __str__(self):
        return self.nome

###     Classe Perfil
###########################
class Perfil(models.Model):
    descricao = models.TextField()
    cidade = models.CharField(max_length=50)
    pais = models.CharField(max_length=30)
    genero = models.CharField(max_length=100)
    autor = models.OneToOneField(Autor, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Informações de Perfil'
    def __str__(self):
        return self.autor.nome

###     Classe Rotulo
###########################
class Rotulo(models.Model):
    titulo = models.CharField(max_length=30)

    class Meta:
        ordering = ['titulo']
        verbose_name = 'Rótulo'
        verbose_name_plural = 'Rótulos'
    def __str__(self):
        return self.titulo

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')
    end_date = models.DateField('Data de Encerramento', null=True)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, null=True)
    rotulos = models.ManyToManyField(Rotulo, verbose_name='Rótulos')

    def __str__ (self):
        return self.question_text

    def publicada_recentemente(self):
	    date_now = timezone.now()
	    return date_now-datetime.timedelta(days=1)<=self.pub_date<=date_now
    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'É recente?'


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ['choice_text']
        verbose_name = 'Opção'
        verbose_name_plural = 'Opções'
    def __str__ (self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from polls.models import Question, Choice
#from django.views import generic

# Create your views here.
def index(request):
    last_questions = Question.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')
    return render(request,'polls/index.html', {'questions': last_questions})

def details(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'polls/details.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        select_choice = question.choice_set.get(pk=request.POST['option'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,'polls/details.html',{'question': question,
        'message': 'Você não selecionou nenhuma opção!'})
    else:
        select_choice.votes = select_choice.votes + 1
        select_choice.save()
        return HttpResponseRedirect(reverse('polls:result', args=[question_id]))

def result(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'polls/result.html',{'question': question})

# def viewQuestions(request):
#    result = Question.objects.all()
#    return render_to_response('polls/viewQuestions.html', {'questions': result})

mysite/polls/templates/polls/details.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <style>
            h3{
                color: red;
            }
        </style>
    </head>
    <body>
        {% if message %}
            <h3> {{message}}</h3>
        {% endif %}

        <p> <a href="{% url 'polls:index' %}"> Voltar a todas as enquetes </a></p>
        <h2> <i>{{ question.question_text }}</i></h2>
        <form method="POST" action="{% url 'polls:vote' question.id %}">
            {% csrf_token %}
            <fieldset>
            {% for choice in question.choice_set.all %}
                <input type="radio" id="question({{forloop.counter}})" name="option" value="{{choice.id}}">
                <label for="question-{{forloop.counter}}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <br>
            <input type="submit" value="Votar">
            <p> </p><a href="{% url 'polls:index' %}">  Cancelar  </a> <p>
            </fieldset>
        </form>
    </body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <style>
        h4:hover{
            color: blue;
        }
        .polls{
            width: 60%;
            margin-left: 0px;
            align: left;
        }
        a{
            text-decoration: none;
            color: black;
        }
        a:hover{
            text-decoration: underline;
        }
    </style>
    <body>
        <h2> Enquetes </h2>
        <hr>
        {% if not questions %}
            <p> Sem enquetes disponíveis </p>
        {% else %}
            {% for question in questions %}
                <h4> <a href="{% url 'polls:details' question.id %} "><i>{{ question.question_text }} </i></a> </h4>
                <p> <a href="{% url 'polls:result' question.id %}"> Ver resultado parcial da enquete</a></p>
                <hr class="polls">
            {% endfor %}
        {% endif %}
    </body>
</html>

mysite/polls/templates/polls/result.html
<!DOCTYPE html>
<html>
    <head>
    <meta charset="UTF-8">
    </head>
    <style>
        table{
            text-align: center;
            width: 50vw;
        }
        th{
            font-style: italic;
        }
    </style>
    <body>
        <p> <a href="{% url 'polls:index' %}"> Voltar a todas as enquetes </a></p>
        <h2> {{ question.question_text }}</h2>
            <table border="2">
                <tr>
                    <th> Opção </th>
                    <th> Votos </th>
                </tr>
                {% for choice in question.choice_set.all %}
                <tr>
                    <td> {{choice.choice_text}} </td>
                    <td> {{choice.votes}} </td>
                </tr>
                {% endfor %}

            </table>
    </body>
</html>

mysite/polls/templates/polls/viewQuestions.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
         {% for question in questions %}
            <p> {{question}} </p>
            {% endfor %}
    </body>
</html>