mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),
    path('polls/',include('polls.urls')),
    path('simuu/',include('simuu.urls'))
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = 'root'
urlpatterns = [
    path('', views.index, name="index"),
]

mysite/simuu/urls.py
from django.urls import path #,include
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'simuu'
urlpatterns = [
	path('', views.ListarSimulados.as_view(), name='listarSimulados'),
	path('listar_questoes/', views.ListarQuestoes.as_view(), name='listarQuestoes'),
	path('responder_simulado/<int:id_simulado>', views.ResponderSimulado.as_view(), name='responderSimulado'),
	path('submeter_simulado/', views.SubmeterFormulario.as_view(), name='submeterSimulado'),
	path('cadastro/', views.Cadastro.as_view(), name='cadastro'),
    path('login/',views.LoginUsuario.as_view(),name='login'),
    path('logout/',login_required(views.LogoutUsuario.as_view()),name='logout')
]

mysite/simuu/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Simulado(models.Model):
    titulo = models.CharField(max_length=200)
    descricao = models.TextField()
    autor = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name_plural = "simulados"

class Questao(models.Model):
    texto = models.TextField()
    pontuacao = models.PositiveIntegerField(default=0)
    simulado = models.ForeignKey('Simulado',on_delete=models.CASCADE)

    def __str__(self):
        return self.texto

    def get_respostas(self):
        return Resposta.objects.filter(questao=self)

    class Meta:
        verbose_name_plural = "questões"

class Resposta(models.Model):
    texto = models.CharField(max_length=200)
    questao = models.ForeignKey('Questao',on_delete=models.CASCADE)
    correta = models.BooleanField(default=False)

    def __str__(self):
        return self.texto

    class Meta:
        verbose_name_plural = "respostas"

mysite/simuu/views.py
from django.shortcuts import render,redirect
from simuu.models import Simulado,Questao,Resposta
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages

# Create your views here.
class ListarSimulados(generic.ListView):
    model = Simulado
    context_object_name = 'simulados'
    template_name = 'simuu/listarSimulados.html'

class ListarQuestoes(generic.ListView):
    model = Questao
    context_object_name = 'questoes'
    template_name = 'simuu/listarQuestoes.html'

class ResponderSimulado(generic.View):
    def get(self, request, *args, **kwargs):
        try:
            simulado = Simulado.objects.get(pk=kwargs['id_simulado'])
        except (KeyError,Simulado.DoesNotExist):
            return redirect('simuu:listarSimulados')
        else:
            questoes = Questao.objects.filter(simulado=simulado)
            context = {'questoes': questoes,'simulado': simulado}
            return render(request,'simuu/responderSimulado.html',context)

class SubmeterFormulario(generic.View):
    def post(self, request, *args, **kwargs):
        try:
            id_simulado = request.POST["id_simulado"]
            simulado = Simulado.objects.get(pk=id_simulado)
        except (KeyError,Simulado.DoesNotExist):
            return redirect('simuu:listarSimulados')
        else:
            pontuacao_total = 0
            pontuacao_usuario = 0
            questoes = Questao.objects.filter(simulado=simulado)

            gabarito = {}

            for questao in questoes:
                resposta_correta = Resposta.objects.get(questao=questao,correta=True)
                resposta_usu = int(request.POST[('questao-'+str(questao.id))])
                resposta = Resposta.objects.get(pk=resposta_usu)

                # Verificar respostas
                if resposta_correta.id == resposta_usu:
                    pontuacao_usuario += questao.pontuacao
                    gabarito[questao] = {True: resposta}
                else:
                    gabarito[questao] = {False: resposta}
                pontuacao_total += questao.pontuacao

            context = {
                'gabarito': gabarito,
                'pontuacao_total': pontuacao_total,
                'pontuacao_usuario': pontuacao_usuario
            }
            return render(request,'simuu/pontuacao.html',context)

    def get(self, request, *args, **kwargs):
        return redirect('simuu:listarSimulados')



class Cadastro(generic.View):
    def get(self, request):
        return render(request,'simuu/cadastro.html')

    def post(self, request):
        caract = 6

        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['first_name']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password != cpassword:
            messages.add_message(request, messages.ERROR, "As senhas não conferem!")
            return redirect('simuu:cadastro')
        elif len(password) < caract:
            messages.add_message(request, messages.ERROR, "A senha precisa ter no mínimo 6 caracteres!")
            return redirect('simuu:cadastro')
        else:
            if User.objects.filter(username = username).first():
                messages.error(request, "Já existe usuário com esse username")
                return redirect('simuu:cadastro')
            User.objects.create_user(username=username,email=email,password=password,first_name=first_name)
            user_logado = authenticate(username=username,password=password)
            login(request,user_logado)
            return redirect('simuu:listarSimulados')



class LoginUsuario(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request,'simuu/login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('simuu:listarSimulados')
        else:
            messages.add_message(request, messages.ERROR,"Usuário ou senha inválidos")
            return redirect('simuu:login')

class LogoutUsuario(generic.View):
    def get(self,request):
        logout(request)
        return redirect('simuu:login')

mysite/simuu/templates/simuu/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block titulo %} {% endblock %} </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function() {
            $(".close").click(function() {
          		$(this).parent().fadeOut();
        	});
        });
    </script>
    <link rel="stylesheet" href="{% static 'simuu/css/main.css' %}" type="text/css">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-4 col-sm-3 col-md-3 menu position-fixed">
                <h3 class="text-center logo"> Simuu </h3>
                <ul class="list-group text-center links">
                    <li class="list-group-item"><a class="link-menu" href="{% url 'simuu:listarSimulados' %}"> Simulados </a></li>
                    <li class="list-group-item"><a class="link-menu" href="{% url 'simuu:listarQuestoes' %}"> Questões </a></li>
                    <!--<li class="list-group-item">Resultados</li>-->
                    {% if request.user.is_authenticated %}
                    <li class="list-group-item"><a class="link-menu" href="{% url 'simuu:logout' %}"> Logout </a></li>
                    {% else %}
                    <li class="list-group-item"><a class="link-menu" href="{% url 'simuu:login' %}"> Login</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-8 offset-4 col-sm-9 offset-sm-3 col-md-9 offset-md-3 conteudo">
                <div class="row">
                    <div class="col-12 col-sm-8 offset-sm-2">
                    {% if messages %}
                        {% for msg in messages %}
                            {% if msg.level_tag == 'error' %}
                                <div class="text-center alert alert-danger alert-dismissible fade show" role="alert">
                                    <strong>{{msg.message}}</strong>
                                    <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close">
                                    X
                                    </button>
                                </div>
                            {% else %}
                                <div class="text-center alert alert-success alert-dismissible fade show" role="alert">
                                    <strong>{{msg.message}}</strong>
                                    <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close">
                                    X
                                    </button>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>
                {% block conteudo %}
    		    {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

mysite/simuu/templates/simuu/cadastro.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title> Simuu </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'simuu/css/main.css' %}" type="text/css">
    <script
			  src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $(".close").click(function() {
          		$(this).parent().fadeOut();
        	});
        });
    </script>
</head>
<body style="background: #0D47A1;">
    <div class="container">
        <div class="row h-100">
            <div class="col-12 col-sm-12 col-md-6 offset-md-3">
                <div class="row h-100 align-items-center">
                    <div class="col-10 offset-1 col-sm-10 offset-sm-1 col-md-10 col-md-offset-1 bg-white pb-5 rounded">
                        <div>
                            <h3 class="logo text-center"> Simuu </h3>
                            <h5 class="text-center"> Cadastro </h5>
                            {% if messages %}
                                {% for msg in messages %}
                                    {% if msg.level_tag == 'error' %}
                                        <div class="text-center alert alert-danger alert-dismissible fade show" role="alert">
                                            <strong>{{msg.message}}</strong>
                                            <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close">
                                            X
                                            </button>
                                        </div>
                                    {% else %}
                                        <div class="text-center alert alert-success alert-dismissible fade show" role="alert">
                                            <strong>{{msg.message}}</strong>
                                            <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close">
                                            X
                                            </button>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            <form class="mx-auto" action="{% url 'simuu:cadastro' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email: </label>
                                    <input type="text" class="form-control" name="email" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Username: </label>
                                    <input type="text" class="form-control" name="username" placeholder="Nome de usuário">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Nome: </label>
                                    <input type="text" class="form-control" name="first_name" placeholder="Nome">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Senha: </label>
                                    <input type="password" class="form-control" name="password" placeholder="Senha">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Confirmar senha: </label>
                                    <input type="password" class="form-control" name="cpassword" placeholder="Senha">
                                </div>
                                <div class="text-center">
                                    <!--<button type="submit" class="btn btn-primary">Esqueci minha senha</button>-->
                                    <a href="{% url 'simuu:login' %}" class="btn btn-secondary"> Login </a>
                                    <button type="submit" class="btn btn-primary">Cadastrar</button>

                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

mysite/simuu/templates/simuu/listarQuestoes.html
{% extends 'simuu/base.html' %}
{% block titulo %}
    Listar Questões - Simuu
{% endblock %}
{% block conteudo %}
    <div class="row row-eq-height mt-4">
        {% for questao in questoes %}
        <div class="col-md-6 col-sm-12 form-group pb-2">
            <div class="card mb-3 text-center">
                <div class="card-body">
                    <h5 class="card-title ">{{questao.texto}}</h5>
                    <p class="card-text text-left"> Alternativas: </p>
                    {% for r in questao.get_respostas %}
                        <p class="card-text text-left"> <strong>{{r}}</strong></p>
                    {% endfor %}

                  <!--<a href="#" class="btn responderSimulado float-right">RESPONDER</a>-->
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

mysite/simuu/templates/simuu/listarSimulados.html
{% extends 'simuu/base.html' %}
{% block conteudo %}
    <div class="row row-eq-height mt-4">
        {% for sim in simulados %}
        <div class="col-md-6 col-sm-12 form-group pb-2">
            <div class="card mb-3 text-center">
                <div class="card-body">
                  <h5 class="card-title">{{sim.titulo}}</h5>
                  <p class="card-text">{{sim.descricao}}</p>
                  <a href="{% url 'simuu:responderSimulado' sim.id %}" class="btn responderSimulado float-right">RESPONDER</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

mysite/simuu/templates/simuu/login.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title> Simuu </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'simuu/css/main.css' %}" type="text/css">
    <script
			  src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $(".close").click(function() {
          		$(this).parent().fadeOut();
        	});
        });
    </script>
</head>
<body style="background: #0D47A1;">
    <div class="container">
        <div class="row h-100">
            <div class="col-12 col-sm-12 col-md-6 offset-md-3">
                <div class="row h-100 align-items-center">
                    <div class="col-10 offset-1 col-sm-10 offset-sm-1 col-md-10 col-md-offset-1 bg-white pb-5 rounded">
                        <div>
                            <h3 class="logo text-center"> Simuu </h3>
                            <h5 class="text-center"> Acessar </h5>
                            {% if messages %}
                                {% for msg in messages %}
                                    {% if msg.level_tag == 'error' %}
                                        <div class="text-center alert alert-danger alert-dismissible fade show" role="alert">
                                            <strong>{{msg.message}}</strong>
                                            <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close">
                                            X
                                            </button>
                                        </div>
                                    {% else %}
                                        <div class="text-center alert alert-success alert-dismissible fade show" role="alert">
                                            <strong>{{msg.message}}</strong>
                                            <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close">
                                            X
                                            </button>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            <form class="mx-auto" action="{% url 'simuu:login' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Username: </label>
                                    <input type="text" class="form-control" name="username" placeholder="Nome de usuário">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Senha: </label>
                                    <input type="password" class="form-control" name="password" placeholder="Senha">
                                </div>
                                <div class="text-center">
                                    <!--<button type="submit" class="btn btn-primary">Esqueci minha senha</button>-->
                                    <a href="{% url 'simuu:cadastro' %}" class="btn"> Cadastrar </a>
                                    <button type="submit" class="btn btn-secondary">Login</button>
                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

mysite/simuu/templates/simuu/pontuacao.html
{% extends 'simuu/base.html' %}
{% block titulo %}
    Pontuação do simulado - Simuu
{% endblock %}
{% block conteudo %}
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-6 rounded border bg-primary border-primary quadro">
                <h2 class="pontuacao">Sua pontuação</h2>
                <h3 class="valor_pontuacao">{{pontuacao_usuario}}</h3>
            </div>
            <div class="col-6 rounded border bg-secondary border-secondary quadro">
                <h2 class="pontuacao">Pontuação total</h2>
                <h3 class="valor_pontuacao">{{pontuacao_total}}</h3>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-12">
                {% for questao,dados in gabarito.items %}
                    {% with outer_counter=forloop.counter %}
                    <div class="form-group w-100">
                        {% for acertou,resposta_usuario in dados.items %}
                            {% if acertou %}
                                <button type="button" class="btn btn-success">
                                    Pontuação <span class="badge badge-light">{{questao.pontuacao}}</span>
                                </button>
                                <div class="alert alert-success">
                                <h4>{{forloop.parentloop.counter}}. {{questao.texto}} </h4>
                                {% for resposta in questao.resposta_set.all %}
                                    {% if resposta.correta %}
                                    <div class="form-check">
                                      <input class="form-check-input" type="radio" name="questao-{{questao.id}}" id="exampleRadios{{resposta.id}}" value="{{resposta.id}}" checked disabled>
                                      <label class="form-check-label font-weight-bold" for="exampleRadios{{resposta.id}}">
                                         {{resposta.texto}}
                                      </label>
                                    </div>
                                    {% else %}
                                    <div class="form-check">
                                      <input class="form-check-input" type="radio" name="questao-{{questao.id}}" id="exampleRadios{{resposta.id}}" value="{{resposta.id}}" disabled>
                                      <label class="form-check-label" for="exampleRadios{{resposta.id}}">
                                         {{resposta.texto}}
                                      </label>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                <p> Sua resposta: {{resposta_usuario}}</p>
                                </div>
                            {% else %}
                                <button type="button" class="btn btn-danger">
                                    Pontuação <span class="badge badge-light">{{questao.pontuacao}}</span>
                                </button>
                                <div class="alert alert-danger">
                                <h4>{{forloop.parentloop.counter}}. {{questao.texto}} </h4>
                                {% for resposta in questao.resposta_set.all %}
                                    {% if resposta.correta %}
                                    <div class="form-check">
                                      <input class="form-check-input" type="radio" name="questao-{{questao.id}}" id="exampleRadios{{resposta.id}}" value="{{resposta.id}}" checked disabled>
                                      <label class="form-check-label font-weight-bold" for="exampleRadios{{resposta.id}}">
                                         {{resposta.texto}}
                                      </label>
                                    </div>
                                    {% else %}
                                    <div class="form-check">
                                      <input class="form-check-input" type="radio" name="questao-{{questao.id}}" id="exampleRadios{{resposta.id}}" value="{{resposta.id}}" disabled>
                                      <label class="form-check-label" for="exampleRadios{{resposta.id}}">
                                         {{resposta.texto}}
                                      </label>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                <p> Sua resposta: {{resposta_usuario}} </p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endwith %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mysite/simuu/templates/simuu/responderSimulado.html
{% extends 'simuu/base.html' %}
{% block titulo %}
    Responder simulado - Simuu
{% endblock %}
{% block conteudo %}
                <div class="container-fluid bg-light">
                    <h2> {{ simulado.titulo }} </h2>
                    <form method="POST" action="{% url 'simuu:submeterSimulado' %}">
                    {% csrf_token %}
                    <input type='number' name="id_simulado" value="{{simulado.id}}" style="display: none;">
                    {% for questao in questoes %}
                        <div class="form-group">
                            <div class="questao">
                            <h4> {{questao.texto}} </h4>
                                {% for resposta in questao.resposta_set.all %}
                                    {% if forloop.first %}
                                    <div class="form-check">
                                      <input class="form-check-input" type="radio" name="questao-{{questao.id}}" id="exampleRadios1" value="{{resposta.id}}" required>
                                      <label class="form-check-label" for="exampleRadios1">
                                         {{resposta.texto}}
                                      </label>
                                    </div>
                                    {% else %}
                                    <div class="form-check">
                                      <input class="form-check-input" type="radio" name="questao-{{questao.id}}" id="exampleRadios1" value="{{resposta.id}}">
                                      <label class="form-check-label" for="exampleRadios1">
                                         {{resposta.texto}}
                                      </label>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary"> Responder Formulário</button>
                    </form>
                </div>
{% endblock %}