mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),
    path('polls/',include('polls.urls')),
    path('simuu/',include('simuu.urls'))
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
	path('', views.index, name='index'),
	path('details/<int:question_id>/',views.details,name='details'),
	path('result/<int:question_id>/',views.result,name='result'),
	path('vote/<int:question_id>/',views.vote,name='vote')
	#path('all/',views.viewQuestions,name='all')
]

mysite/root/urls.py
from django.urls import path
from . import views

app_name = 'root'
urlpatterns = [
    path('', views.index, name="index"),
]

mysite/simuu/urls.py
from django.urls import path #,include
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'simuu'
urlpatterns = [
	path('', views.ListarSimulados.as_view(), name='listarSimulados'),
	path('listar_questoes/', views.ListarQuestoes.as_view(), name='listarQuestoes'),
	path('responder_simulado/<int:id_simulado>', views.ResponderSimulado.as_view(), name='responderSimulado'),
	path('submeter_simulado/', views.SubmeterFormulario.as_view(), name='submeterSimulado'),
	path('cadastro/', views.Cadastro.as_view(), name='cadastro'),
    path('login/',views.LoginUsuario.as_view(),name='login'),
    path('logout/',login_required(views.LogoutUsuario.as_view()),name='logout')
]

mysite/root/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'root/index.html')

mysite/root/templates/root/index.html
<html>
    <head>
        <title>Aplicações DSWeb 2021.1</title>
    </head>
    <body>
        <h2>Aplicações da Disciplina DSWeb - 2021.1</h2>
        <hr/>
        <h4>
            <a href="{% url 'polls:index' %}">
                Aplicação de Enquetes (módulo 01)
            </a>
        </h4>
        <h4>
            <a href="{% url 'simuu:listarSimulados' %}">
                Projeto da Disciplina (módulo 02)
            </a>
        </h4>
        <hr/>
    </body>
</html>